services:
  # Backend API Service
  - type: web
    name: lancei-essa-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: API_BASE_URL
        value: https://lancei-essa-api.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      # Não precisamos mais definir esses valores pois usamos método desktop para autenticação
      - key: YOUTUBE_EMERGENCY_MODE
        value: "true"
      # Mantendo esses valores como valores vazios para compatibilidade, mas não são usados
      - key: YOUTUBE_CLIENT_ID
        value: ""
      - key: YOUTUBE_CLIENT_SECRET
        value: ""
      - key: YOUTUBE_REDIRECT_URI
        value: ""
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: INSTAGRAM_CLIENT_ID
        sync: false
      - key: INSTAGRAM_CLIENT_SECRET
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    
  # Frontend Service
  - type: web
    name: lancei-essa-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start-prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: lancei-essa-api
          type: web
          property: url